env="dev"
domain = "gin.com"
host = "127.0.0.1"
name = "gin app"
port = ":8089"
assetUrl="http://localhost/"
dsn = "root:password@tcp(127.0.0.1:3306)/go_test?charset=utf8mb4&parseTime=True&loc=Local"

[email]
host = "smtp.exmail.qq.com"
password = ""
port = 465
sendname = "send name"
tomail = "name@mai.com"
username = "admin@mail.com"